version: 3

tasks:
  migrate:
    desc: "performs data migrations"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./migrations
  migrate-tesk:
    desc: "performs data migrations for test"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  auth:
    desc: "starts grpc auth service"
    cmds:
      - go run ./cmd/sso --config=./config/local.yaml
